#use NGINX as base image
FROM nginx:latest

#copy html files to the container
COPY index.html /usr/share/nginx/html/

#expose port 80 & 443 for incoming traffic
EXPOSE 80 443

#Start NGINX server on container launch
CMD ["nginx", "-g", "daemon off;"]